import { Metadata } from "next";
import "@styles/global.css";
import NavBar from "@components/NavBar";
import { Providers } from "@app/providers";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
    <body>
        <div className='main'>
          <div className='gradient' />
        </div>
        <main className='app'>
          <Providers>
          <NavBar />
          {children}
          </Providers>
        </main>
        {/* <Footer /> */}
    </body>
  </html>
);
}